[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geo_gremlin"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "logkit>=0.1.0",
]
authors = [
    { name = "Illia Ovcharenko" }
]

[project.optional-dependencies]
vector = [
    "numpy>=1.24",
    "pandas>=2.0",
    "geopandas>=1.0",
    "shapely>=2.0",
    "rtree>=1.0",
    "tqdm>=4.65",
    "matplotlib>=3.7",
]
raster = [
    "numpy>=1.24",
    "pandas>=2.0",
    "geopandas>=1.0",
    "shapely>=2.0",
    "tqdm>=4.65",
    "rasterio>=1.3",
    "opencv-python-headless>=4.8",
    "aiohttp>=3.9",
    "aiofiles>=23.2",
    "mercantile>=1.2",
]
cli = [
    "fire>=0.6",
]
gdal = [
    "GDAL",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
